package com.example

import com.example.data.AnimScript
import com.example.data.AppJson
import kotlinx.serialization.decodeFromString

/**
 * Loads the committed test resources (WP0.3). Scripts go through the app's real parser,
 * `AppJson.storage.decodeFromString<AnimScript>`, the same call MainViewModel uses when a script
 * is pasted or imported.
 */
object Fixtures {

    /** The legacy-script corpus, generated by tools/fixtures/gen_fixtures.py. */
    val SCRIPT_NAMES = listOf(
        "01_minimal",
        "02_poses_expressions",
        "03_camera_scene_captions",
        "04_overlays",
        "05_sound_effects",
        "06_long_dense",
        "07_edge_cases"
    )

    fun text(resourcePath: String): String {
        val stream = Fixtures::class.java.getResourceAsStream("/$resourcePath")
            ?: error("Missing test resource: $resourcePath")
        return stream.bufferedReader(Charsets.UTF_8).use { it.readText() }
    }

    fun scriptText(name: String): String = text("fixtures/$name.json")

    fun script(name: String): AnimScript = AppJson.storage.decodeFromString<AnimScript>(scriptText(name))

    /** JSON captured from the baseline app (commit eb6b0b3) before any V2 field existed. */
    fun legacyJson(name: String): String = text("fixtures/legacy_json/$name.json")
}
